name: helaqc-2.0
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bioconda::msgf_plus=2019.07.03
  - bioconda::hardklor=2.3.0
  - bioconda::kronik=2.20
  - bioconda::dinosaur=1.1.3
    #- bioconda::msstitch=2.19
  - bioconda::percolator=3.4
