name: helaqc-2.2
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bioconda::msgf_plus=2020.06.22
  - bioconda::dinosaur=1.2.0
  - bioconda::msstitch=3.3
  - bioconda::percolator=3.4
